[package]
name = "iota-streams-api"
version = "0.0.1"
authors = ["huhn511 <huhneinfachIOTA.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"